### ISSUE TITLE
Add midi-include for all files

### ISSUE THREAD

**Issue by Kongzhu79** [Snapsakademien/scores-ly#4]
Add midi-include for all files. See DaneLiksom for reference. Include should be added in the beginning (for volume setting) and at the end for actual output.

**Comment by tskarhed** [comment]
Could just convention work for TTBB? With the naming

- \tOne
- \tTwo
- \bOne
- \bTwo

And you could include the same file for 90% of the cases.

**Comment by Kongzhu79** [comment]
Yes, the convention is ok. The problem is the tempo-mark. This can be solved by making a centralised include-file for three, four or n number of parts and then include the section from this into the midiXX-file. Could not make it work, have to continue trying.

**Comment by Kongzhu79** [comment]
Fixed at the moment using separate midi.ly for each song.
